//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models.bfc
{
    using System;
    using System.Collections.Generic;
    
    public partial class CobrosEncabezado
    {
        public int Id { get; set; }
        public int IdEmpresa { get; set; }
        public int Anno { get; set; }
        public int Mes { get; set; }
        public int Dia { get; set; }
        public System.DateTime PeriodoDesde { get; set; }
        public System.DateTime PeriodoHasta { get; set; }
        public decimal UF { get; set; }
        public Nullable<decimal> Almacenaje { get; set; }
        public Nullable<decimal> CargaPalletizada { get; set; }
        public Nullable<decimal> DescargaPalletizada { get; set; }
        public int FormaCobro { get; set; }
        public decimal Cantidad { get; set; }
        public bool IsPublicado { get; set; }
    }
}
