//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models.bfc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WEB_BevfoodCenterEntities : DbContext
    {
        public WEB_BevfoodCenterEntities()
            : base("name=WEB_BevfoodCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CobrosEncabezado> CobrosEncabezado { get; set; }
        public virtual DbSet<DocumentoReferencia> DocumentoReferencia { get; set; }
        public virtual DbSet<Log> Log { get; set; }
        public virtual DbSet<ValorCobroEmpresa> ValorCobroEmpresa { get; set; }
    }
}
