//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.Models.bfc
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValorCobroEmpresa
    {
        public int IdEmpresa { get; set; }
        public decimal MetroCuadrado { get; set; }
        public decimal MetroCubico { get; set; }
        public decimal PosicionPalet { get; set; }
        public string ValorDefault { get; set; }
    }
}
